<?php

return [
    'provinces' => [
        'Álava' => 'Álava',
        'Albacete' => 'Albacete',
        'Alicante' => 'Alicante',
        'Almería' => 'Almería',
        'Asturias' => 'Asturias',
        'Ávila' => 'Ávila',
        'Badajoz' => 'Badajoz',
        'Barcelona' => 'Barcelona',
        'Burgos' => 'Burgos',
        'Cáceres' => 'Cáceres',
        'Cádiz' => 'Cádiz',
        'Cantabria' => 'Cantabria',
        'Castellón' => 'Castellón',
        'Ciudad Real' => 'Ciudad Real',
        'Córdoba' => 'Córdoba',
        'Cuenca' => 'Cuenca',
        'Gerona' => 'Gerona',
        'Granada' => 'Granada',
        'Guadalajara' => 'Guadalajara',
        'Gipuzkoa' => 'Gipuzkoa',
        'Huelva' => 'Huelva',
        'Huesca' => 'Huesca',
        'Islas Baleares' => 'Islas Baleares',
        'Jaén' => 'Jaén',
        'La Coruña' => 'La Coruña',
        'La Rioja' => 'La Rioja',
        'Las Palmas' => 'Las Palmas',
        'León' => 'León',
        'Lleida' => 'Lleida',
        'Madrid' => 'Madrid',
        'Málaga' => 'Málaga',
        'Murcia' => 'Murcia',
        'Navarra' => 'Navarra',
        'Ourense' => 'Ourense',
        'Palencia' => 'Palencia',
        'Pontevedra' => 'Pontevedra',
        'Salamanca' => 'Salamanca',
        'Segovia' => 'Segovia',
        'Sevilla' => 'Sevilla',
        'Soria' => 'Soria',
        'Tarragona' => 'Tarragona',
        'Teruel' => 'Teruel',
        'Toledo' => 'Toledo',
        'Valencia' => 'Valencia',
        'Valladolid' => 'Valladolid',
        'Vizcaya' => 'Vizcaya',
        'Zamora' => 'Zamora',
        'Zaragoza' => 'Zaragoza',
    ],

    'difficulties' => [
        'Fácil' => 'Fácil',
        'Moderado' => 'Moderado',
        'Difícil' => 'Difícil',
    ],
];
